server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1j84i84c5876n62qo.mysql.rds.aliyuncs.com:3306/spring_db?allowMultiQueries=true
    username: fhuurr_admin
    # need to change the password here if the device is different
    password: BJYbae-7532154

  redis:
    host: redis-14587.c54.ap-northeast-1-2.ec2.cloud.redislabs.com
    port: 14587
    password: BJYbae-7532154
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.data.spring.dataspringhandler.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  #  support-methods-arguments: true
  params: count=countsql

